[package]
name = "mud_host"
version = "0.1.0"
authors = ["Chris Chalstrom <chris.chalstrom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mud_host"
path = "src/lib.rs"

[dependencies]
